# Generated by Django 5.0.6 on 2026-08-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100)),
                ('ville', models.CharField(default='Abidjan', max_length=100)),
                ('tarif_fcfa', models.PositiveIntegerField(help_text='Frais de livraison en FCFA')),
                ('delai_estime', models.CharField(default='24-48h', max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('commune', 'ville')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=150)),
                ('client_telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('mode_paiement', models.CharField(choices=[('livraison', 'Paiement à la livraison'), ('mobile_money', 'Mobile Money')], default='livraison', max_length=20)),
                ('acompte_fcfa', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('confirmee', 'Confirmée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('zone_livraison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.deliveryzone')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prix_achat_fcfa', models.PositiveIntegerField(help_text='Prix de gros chez le fournisseur')),
                ('prix_vente_fcfa', models.PositiveIntegerField(help_text='Prix affiché au client')),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('bracelet', models.CharField(blank=True, choices=[('cuir', 'Cuir'), ('acier', 'Acier'), ('silicone', 'Silicone')], max_length=20)),
                ('mouvement', models.CharField(blank=True, choices=[('quartz', 'Quartz'), ('automatique', 'Automatique')], max_length=20)),
                ('etanche', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire_fcfa', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/')),
                ('principale', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
    ]
