# Generated by Django 5.0.6 on 2026-08-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ancien_prix_fcfa',
            field=models.PositiveIntegerField(blank=True, help_text='Pour afficher une promo barrée', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='diametre',
            field=models.CharField(blank=True, help_text='Ex. 41 mm', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='garantie',
            field=models.CharField(blank=True, help_text='Ex. 24 mois', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='marque',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='matiere',
            field=models.CharField(blank=True, help_text='Ex. Acier inoxydable 316L', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='popularite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, choices=[('Luxe', 'Luxe'), ('Sport', 'Sport'), ('Classique', 'Classique')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
