# Generated by Django 5.0.6 on 2026-08-04 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_ancien_prix_fcfa_product_diametre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('traite', models.BooleanField(default=False, help_text='Coche une fois que tu as répondu')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('publie', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Question fréquente',
                'verbose_name_plural': 'Questions fréquentes',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('note', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texte', models.TextField()),
                ('publie', models.BooleanField(default=True, help_text="Décoche pour retirer l'avis du site")),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['ordre', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default="MONTR'OR", max_length=80)),
                ('slogan', models.CharField(default="L'élégance accessible", max_length=120)),
                ('telephone_affichage', models.CharField(default='07 01 85 07 08', max_length=30)),
                ('telephone_tel', models.CharField(default='+2250701850708', help_text="Format international, pour le lien d'appel", max_length=30)),
                ('whatsapp', models.CharField(default='2250701850708', help_text='Sans + ni espaces, pour wa.me', max_length=30)),
                ('email', models.EmailField(default='contact@montror.ci', max_length=254)),
                ('adresse', models.CharField(default="Cocody Angré, Abidjan, Côte d'Ivoire", max_length=255)),
                ('horaires', models.CharField(default='Lun – Sam : 08h – 20h', max_length=120)),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-cree_le']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-principale', 'ordre', 'id']},
        ),
        migrations.AddField(
            model_name='order',
            name='frais_livraison_fcfa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='maj_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note_interne',
            field=models.TextField(blank=True, help_text="Visible seulement dans l'admin"),
        ),
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro communiqué au client, ex. MO-4F82K1', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='nom_produit',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='productimage',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la galerie"),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_telephone',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
