# Generated by Django 5.0.6 on 2026-08-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contactmessage_faq_review_sitesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='negociable',
            field=models.BooleanField(default=False, help_text='Affiche un bouton « Négocier avec notre équipe » sur la fiche produit'),
        ),
        migrations.AddField(
            model_name='product',
            name='note_interne',
            field=models.TextField(blank=True, help_text='Notes de catalogage, alertes marque… Visible seulement ici.'),
        ),
        migrations.AddField(
            model_name='product',
            name='publie',
            field=models.BooleanField(default=True, help_text='Décoche pour retirer complètement le produit du site (il reste en base)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bracelet',
            field=models.CharField(blank=True, choices=[('cuir', 'Cuir'), ('acier', 'Acier'), ('silicone', 'Silicone'), ('velcro', 'Velcro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Décoche pour afficher « Rupture »'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix_achat_fcfa',
            field=models.PositiveIntegerField(blank=True, help_text='Prix de gros chez le fournisseur. Jamais affiché sur le site.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix_vente_fcfa',
            field=models.PositiveIntegerField(blank=True, help_text='Prix affiché au client. Laisser vide pour un produit à négocier de A à Z.', null=True),
        ),
    ]
