# Generated by Django 5.0.6 on 2026-08-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_negociable_product_note_interne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='produits/videos/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('mise_en_avant', models.BooleanField(default=False, help_text="Coche pour utiliser cette vidéo dans la vitrine animée de l'accueil")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='shop.product')),
            ],
            options={
                'verbose_name': 'Vidéo produit',
                'verbose_name_plural': 'Vidéos produit',
                'ordering': ['-mise_en_avant', 'ordre', 'id'],
            },
        ),
    ]
