# Generated by Django 5.0.6 on 2026-08-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fonctions',
            field=models.TextField(blank=True, help_text="Une fonction par ligne (ex. « Guichet dateur à 6h »). N'y mettre que ce qui est visible sur la montre."),
        ),
        migrations.AddField(
            model_name='product',
            name='livre_avec',
            field=models.CharField(blank=True, help_text='Ex. « Coffret rigide finition bois + coussinet »', max_length=200),
        ),
    ]
