# Generated by Django 5.0.6 on 2026-08-10 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_fonctions_product_livre_avec'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acompte_pourcent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = payable intégralement à la livraison. 50 = un acompte de 50 %% est demandé avant expédition (pièces chères ou sur commande).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode_paiement',
            field=models.CharField(choices=[('livraison', 'Paiement à la livraison'), ('immediat', "Payé d'avance (Mobile Money)"), ('acompte', 'Acompte versé, solde à la livraison'), ('mobile_money', 'Mobile Money')], default='livraison', max_length=20),
        ),
    ]
