# Generated by Django 5.0.6 on 2026-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_acompte_pourcent_alter_order_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mise_en_avant',
            field=models.BooleanField(default=True, help_text="Autorise l'affichage en vitrine (accueil, hero). Décoche pour un produit qui reste au catalogue mais qu'on ne met pas en avant — photo montrant un emballage de marque, visuel à retoucher…"),
        ),
    ]
