# Generated by Django 5.0.6 on 2026-08-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_mise_en_avant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_livraison',
            field=models.CharField(choices=[('yango', 'Livraison à domicile (Yango)'), ('jumia_relais', 'Point Relais Jumia')], default='yango', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode_paiement',
            field=models.CharField(choices=[('livraison', 'Paiement à la livraison'), ('mobile_money', "Mobile Money (payé d'avance)"), ('acompte_50', 'Acompte 50 % + solde à la livraison')], default='livraison', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='zone_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.deliveryzone'),
        ),
        migrations.CreateModel(
            name='JumiaPickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.TextField()),
                ('actif', models.BooleanField(default=True, help_text="Décoche tant que l'adresse n'est pas assez précise pour un client")),
            ],
            options={
                'verbose_name': 'Point relais Jumia',
                'verbose_name_plural': 'Points relais Jumia',
                'ordering': ['commune', 'nom'],
                'unique_together': {('commune', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='point_relais',
            field=models.ForeignKey(blank=True, help_text='Renseigné uniquement si le mode de livraison est « Point Relais Jumia »', null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.jumiapickuppoint'),
        ),
    ]
