# Generated by Django 5.0.6 on 2026-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_latitude_order_longitude_order_mode_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tarif_point_relais_fcfa',
            field=models.PositiveIntegerField(default=800, help_text='Frais facturés pour un retrait en point relais Jumia'),
        ),
    ]
