# Generated by Django 5.0.6 on 2026-08-13 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(db_index=True, max_length=20)),
                ('empreinte', models.CharField(max_length=64)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('essais', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'code de vérification',
                'verbose_name_plural': 'codes de vérification',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='SessionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreinte_cle', models.CharField(db_index=True, max_length=64, unique=True)),
                ('appareil', models.CharField(blank=True, max_length=60)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('vue_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session client',
                'verbose_name_plural': 'sessions client',
                'ordering': ['-vue_le'],
            },
        ),
    ]
