# Generated by Django 5.0.6 on 2026-08-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_codeverification_sessionclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeVerification',
        ),
    ]
