# Generated by Django 5.0.6 on 2026-08-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_codecourriel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeCourriel',
        ),
    ]
