# Generated by Django 5.0.6 on 2026-08-13 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_delete_codecourriel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCourriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.EmailField(max_length=254)),
                ('usage', models.CharField(choices=[('verification', "Vérification de l'adresse"), ('reinitialisation', 'Réinitialisation du mot de passe')], max_length=20)),
                ('empreinte', models.CharField(max_length=64)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('essais', models.PositiveSmallIntegerField(default=0)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_courriel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code e-mail',
                'verbose_name_plural': 'codes e-mail',
                'ordering': ['-cree_le'],
            },
        ),
    ]
