# Generated by Django 5.2.17 on 2026-08-16 01:17

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_codecourriel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(storage=shop.models.stockage_videos, upload_to='produits/videos/'),
        ),
    ]
