# Generated by Django 5.2.17 on 2026-08-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_alertes',
            field=models.EmailField(blank=True, help_text="Adresse prévenue à chaque nouvelle commande. Laisser vide pour ne recevoir aucun message. Différente de l'e-mail de contact affiché sur le site.", max_length=254),
        ),
    ]
