# Generated by Django 5.2.17 on 2026-08-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_sitesettings_email_alertes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(unique=True, verbose_name='jour')),
                ('visites', models.PositiveIntegerField(default=0, verbose_name='visites')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='pages vues')),
            ],
            options={
                'verbose_name': 'fréquentation',
                'verbose_name_plural': 'fréquentation',
                'ordering': ['-jour'],
            },
        ),
    ]
